var option = {
	title:{
		text:'条形图'
	},
	legend:{
		data:['数据指标名称1','数据指标名称2'...]
	},
	xAxis:{
		type:'value'
	},
	yAxis:{
		type:'category',
		data:['y轴刻度名称1','y轴刻度名称2',...]
	},
	series:[
		{
			name:'数据指标名称1',
			data:[y轴刻度名称1在数据指标名称1的表现,y轴刻度名称2在数据指标名称1的的表现,...]
		},
		{
			name:'数据指标名称2',
			data:[y轴刻度名称1在数据指标名称2的表现,y轴刻度名称2在数据指标名称2的的表现,...]
		},
			...
		]
}